NAME_DISPLAY_MAP: dict = {
    "vt_symbol": "Local code",
    "direction": "Direction",
    "price": "Price",
    "volume": "Order volume",
    "time": "Execution time（seconds）",
    "interval": "Interval（seconds）",
    "offset": "Offset",
    "status": "Algo status",
    "traded_price": "Avg trade price",
    "traded": "Trade volume",
    "left": "Remaining volume",
    "order_volume": "Single order",
    "timer_count": "Current count",
    "total_count": "Total count",
    "template_name": "Algo template",
    "display_volume": "Display volume",
    "price_add": "Price offset",
    "step_price": "Grid spacing",
    "step_volume": "Grid volume",
    "order_type": "Order type",
    "active_vt_symbol": "Active leg",
    "passive_vt_symbol": "Passive leg",
    "spread_up": "Spread upper limit",
    "spread_down": "Spread lower limit",
    "max_pos": "Max position",
    "start_time": "Start time",
    "end_time": "End time",
    "min_volume": "Min order volume",
    "max_volume": "Max order volume",
    "volume_change": "Volume change"
}
